sudo: required
services:
  - docker

before_install:
  - docker build -t swa181/react-test -f ./client/Dockerfile.dev ./client 

script:
  # makes sure the test script exits with status codes
  - docker run swa181/react-test npm test -- --coverage

after_success:
  - docker build -t swa181/multi-client ./client
  - docker build -t swa181/multi-nginx ./nginx
  - docker build -t swa181/multi-server ./server
  - docker build -t swa181/multi-worker ./worker
  # Log in to the docker CLI
  # the echo adds in the password through stdin
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push swa181/multi-client
  - docker push swa181/multi-nginx
  - docker push swa181/multi-server
  - docker push swa181/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-739400692698
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY